spring.application.name=crypto-trading
spring.datasource.url=jdbc:h2:mem:crypto-trading
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
api.binance.base-url=https://api.binance.com
api.binance.tickers.path=/api/v3/ticker/bookTicker
api.huobi.base-url=https://api.huobi.pro
api.huobi.tickers.path=/market/tickers
crypto.tickers.supported=ETHUSDT,BTCUSDT
scheduler.price-poll-interval-ms=10000
