INSERT INTO WALLET_BALANCE (USER_ID, ASSET, BALANCE) VALUES (1, 'USDT', 50000);
INSERT INTO WALLET_BALANCE (USER_ID, ASSET, BALANCE) VALUES (1, 'ETHUSDT', 0);
INSERT INTO WALLET_BALANCE (USER_ID, ASSET, BALANCE) VALUES (1, 'BTCUSDT', 0);