-- Init tables --
DROP TABLE IF EXISTS TICKER_AGG_PRICE;
CREATE TABLE TICKER_AGG_PRICE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    SYMBOL VARCHAR(50),
    BEST_BID DECIMAL(19,8),
    BEST_ASK DECIMAL(19,8),
    CREATED_DATE TIMESTAMP
);

DROP TABLE IF EXISTS WALLET_BALANCE;
CREATE TABLE WALLET_BALANCE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT,
    ASSET VARCHAR(50),
    BALANCE  DECIMAL(19,8)
);

DROP TABLE IF EXISTS TRADE_TRANSACTION;
CREATE TABLE TRADE_TRANSACTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT,
    SYMBOL VARCHAR(50),
    TRADE_ACTION VARCHAR(10),
    PRICE DECIMAL(19,8),
    QUANTITY DECIMAL(19,8),
    TOTAL DECIMAL(19,8),
    TRANSACTION_DATE_TIME TIMESTAMP
);