-- Init tables --
DROP TABLE IF EXISTS TICKER_AGG_PRICE;
CREATE TABLE TICKER_AGG_PRICE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    SYMBOL VARCHAR(50),
    BEST_BID DECIMAL(19,8),
    BEST_ASK DECIMAL(19,8),
    CREATED_DATE TIMESTAMP
);